source 'https://rubygems.org'
ruby '2.7.0'

gem 'bundler'
gem 'rake',    '13.0.3'
gem 'sinclair', '1.6.7'

group :development, :test do
  gem 'pry',        '0.12.2'
  gem 'pry-nav',    '0.3.0'
  gem 'simplecov',  '0.17.1'
  gem 'rubycritic', '4.6.1'
  gem 'yard',       '0.9.26'
  gem 'yardstick',  '0.9.9'
end

group :development do
  gem 'reek',          '6.0.3'
  gem 'rubocop',       '0.80.1'
  gem 'rubocop-rspec', '1.38.1'
end

group :test do
  gem 'rspec',                     '3.9.0'
  gem 'rspec-collection_matchers', '1.2.0'
  gem 'rspec-core',                '3.9.3'
  gem 'rspec-expectations',        '3.9.4'
  gem 'rspec-mocks',               '3.9.1'
  gem 'rspec-support',             '3.9.4'
end
