source 'https://rubygems.org'
ruby '2.7.0'

gem 'bundler',  '2.4.8'
gem 'rake',     '13.0.6'
gem 'sinclair', '1.8.0'

group :development, :test do
  gem 'pry',        '0.14.1'
  gem 'pry-nav',    '1.0.0'
  gem 'simplecov',  '0.21.2'
  gem 'rubycritic', '4.7.0'
  gem 'yard',       '0.9.27'
  gem 'yardstick',  '0.9.9'
end

group :development do
  gem 'reek',          '6.0.3'
  gem 'rubocop',       '0.80.1'
  gem 'rubocop-rspec', '1.38.1'
end

group :test do
  gem 'minitest',                  '5.16.2'
  gem 'rspec',                     '3.11.0'
  gem 'rspec-collection_matchers', '1.2.0'
  gem 'rspec-core',                '3.11.0'
  gem 'rspec-expectations',        '3.11.0'
  gem 'rspec-mocks',               '3.11.1'
  gem 'rspec-support',             '3.11.0'
end
