source 'https://rubygems.org'
ruby '2.4.0'

gem 'rails', '~> 5.1.x'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'rails_12factor', group: :production
gem 'spring',        group: :development
gem 'darthjee-core_ext'
gem 'tarquinn'
gem 'bower-rails', '~> 0.11.0'
gem 'sinclair'
gem 'rake', '>= 12.3'

group :development, :test do
  gem 'factory_bot'
  gem 'rspec-rails'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'zonebie'
  gem 'simplecov'
  gem 'rspec-collection_matchers'
  gem 'rails-controller-testing'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
end

group :test do
  gem 'webmock'
end
