source 'https://rubygems.org'
ruby '3.3.1'

gem 'bundler',           '2.6.8'
gem 'darthjee-core_ext', '2.0.0'
gem 'puma',              '6.0.0'
gem 'rack',              '2.2.6.3'
gem 'rake',              '13.2.1'
gem 'rails',             '7.2.2.1'
gem 'sass-rails',        '6.0.0'
gem 'uglifier',          '4.2.0'
gem 'nokogiri',          '1.18.8'
gem 'turbolinks',        '5.2.1'
gem 'newrelic_rpm',      '8.12.0'
gem 'sinclair',          '3.0.0'
gem 'tzinfo-data',       '1.2023.3'

group :development, :test do
  gem 'pry',        '0.14.2'
  gem 'pry-nav',    '1.0.0'
  gem 'pry-rails',  '0.3.9'
  gem 'simplecov',  '0.22.0'
  gem 'yard',       '0.9.37'
  gem 'yardstick',  '0.9.9'
  gem 'zyra',       '1.2.0'
end

group :development do
  gem 'rubycritic',    '4.9.2'
  gem 'reek',          '6.4.0'
  gem 'rubocop',       '1.75.5'
  gem 'rubocop-rspec', '3.6.0'
  gem 'zonebie',       '0.6.1'
  gem 'web-console',   '4.2.0'
end

group :test do
  gem 'factory_bot',               '6.2.1'
  gem 'rails-controller-testing',  '1.0.5'
  gem 'rspec',                     '3.13.0'
  gem 'rspec-collection_matchers', '1.2.1'
  gem 'rspec-core',                '3.13.3'
  gem 'rspec-expectations',        '3.13.3'
  gem 'rspec-mocks',               '3.13.2'
  gem 'rspec-rails',               '8.0.0'
  gem 'rspec-support',             '3.13.2'
  gem 'shoulda-matchers',          '5.3.0'
  gem 'timecop',                   '0.9.6'
  gem 'webmock',                   '3.18.1'
end
