FROM ruby:2.4.0

RUN useradd -u 1000 app; \
    mkdir -p /home/app; \
    chown app.app /home/app

RUN apt-get update && apt-get install -y netcat nodejs-legacy npm

RUN npm install bower -g
RUN gem install bundler
