FROM darthjee/taa:0.2.0 as source

FROM darthjee/circleci_rails_bower:0.2.0

USER root
COPY --from=source /usr/local/bundle /usr/local/bundle
COPY --from=source /home/app/app/bower_components /home/circleci/app/bower_components
RUN chown circleci.circleci /home/circleci/app/bower_components /usr/local/bundle -R
USER circleci
