FROM darthjee/rails_bower:0.2.1 as builder

ADD taa_home/* /home/app/app/

WORKDIR /home/app/app
RUN bundle install --clean

USER app
RUN bower install

#FINAL BUILD
FROM darthjee/rails_bower:0.2.1

USER root
COPY --from=builder /usr/local/bundle /usr/local/bundle
COPY --from=builder /home/app/.cache /home/app/.cache
RUN chown app.app /home/app/.cache /usr/local/bundle -R
USER app
