FROM darthjee/circleci_ruby_250:0.1.0

RUN mkdir -p /home/circleci/app

USER root
RUN curl -sL https://deb.nodesource.com/setup_10.x | /bin/bash
RUN apt-get update && apt-get install -y netcat nodejs
USER circleci
