FROM darthjee/circleci_taa:0.2.1 as source

ADD taap_home/* /home/circleci/project/

RUN bundle install --clean
RUN bower install

#FINAL BUILD
FROM darthjee/circleci_taa:0.2.1

USER root
RUN apt-get update && apt-get install -y gnuplot texlive-math-extra

USER root
COPY --chown=circleci:circleci --from=source /usr/local/bundle /usr/local/bundle
COPY --chown=circleci:circleci --from=source /home/circleci/.cache /home/circleci/.cache

USER circleci
