FROM darthjee/rails_bower:0.2.0

ADD taa_home/* /home/app/app/

WORKDIR /home/app/app
RUN bundle install --clean

USER app
RUN bower install

FROM darthjee/rails_bower:0.2.0

COPY --from=builder /usr/local/bundle /usr/local/bundle
COPY --from=builder /home/app/app/bower_components /home/app/app/bower_components
