FROM darthjee/circleci_ruby_node:0.2.1 as source

USER root
RUN npm install bower -g

ADD rails_bower_home/* /home/circleci/project/

RUN bundle install --clean

USER circleci
RUN bower install

#FINAL IMAGE
FROM darthjee/circleci_ruby_node:0.2.1

USER root
RUN npm install bower -g

COPY --from=source /usr/local/bundle /usr/local/bundle
COPY --from=source /home/circleci/.cache /home/circleci/.cache
RUN chown circleci.circleci /home/circleci/.cache /usr/local/bundle -R

USER circleci
