FROM darthjee/taa:0.2.1 as builder

ADD taap_home/* /home/app/app/

WORKDIR /home/app/app

USER root
RUN bundle install --clean

#FINAL BUILD
FROM darthjee/taa:0.2.1

USER root
RUN apt-get update && apt-get install -y gnuplot texlive-math-extra

COPY --from=builder /usr/local/bundle /usr/local/bundle
COPY --from=builder /home/app/.cache /home/app/.cache
RUN chown app.app /home/app/.cache /usr/local/bundle -R
USER app
