FROM darthjee/circleci_rails_bower:0.2.0 as source

WORKDIR /home/circleci/project/

ADD taa_home/* /home/circleci/project/
RUN bundle install --clean
RUN bower install

FROM darthjee/circleci_rails_bower:0.2.0

USER root
COPY --from=source /usr/local/bundle /usr/local/bundle
COPY --from=source /home/circleci/.cache /home/circleci/.cache
RUN chown circleci.circleci /home/circleci/.cache /usr/local/bundle -R
USER circleci
