FROM darthjee/rails_bower:0.2.0 as source

FROM darthjee/circleci_ruby_node:0.2.0

USER root
RUN npm install bower -g

COPY --from=source /usr/local/bundle /usr/local/bundle
COPY --from=source /home/app/app/bower_components /home/circleci/app/bower_components

USER circleci
