FROM darthjee/ruby_node:0.2.1 as builder

USER root
RUN npm install bower -g

ADD rails_bower_home/* /home/app/app/

RUN bundle install --clean

USER app
RUN bower install

#######################
#FINAL IMAGE
FROM darthjee/ruby_node:0.2.1

USER root
RUN npm install bower -g

COPY --chown=app:app --from=builder /usr/local/bundle /usr/local/bundle
COPY --chown=app:app --from=builder /home/app/.cache /home/app/.cache

USER app
