FROM darthjee/rails_bower:0.2.2 as builder

ADD taa_home/* /home/app/app/

RUN bundle install --clean

RUN bower install

#######################
#FINAL BUILD
FROM darthjee/rails_bower:0.2.2

USER root
COPY --chown=app:app --from=builder /usr/local/bundle /usr/local/bundle
COPY --chown=app:app --from=builder /home/app/.cache /home/app/.cache

USER app
