FROM darthjee/ruby_node:0.2.1 as builder

USER root
RUN npm install bower -g

ADD rails_bower_home/* /home/app/app/

RUN bundle install --clean

USER app
RUN bower install

#FINAL IMAGE
FROM darthjee/ruby_node:0.2.1

USER root
RUN npm install bower -g

COPY --from=builder /usr/local/bundle /usr/local/bundle
COPY --from=builder /home/app/.cache /home/app/.cache
RUN chown app.app /home/app/.cache /usr/local/bundle -R

USER app
