version: '3'
services:
  circleci_ruby_250_test: &base
    image: $IMAGE_NAME
    build:
      dockerfile: Dockerfile.test
      context: ./
      args:
        - VERSION=$VERSION
        - IMAGE=$IMAGE
        - DOCKER_ID_USER=$DOCKER_ID_USER
    command: /home/test/test.sh
