source 'https://rubygems.org'
ruby '3.3.1'

gem 'bundler',       '2.5.13'
gem 'rake',          '13.2.1'
gem 'sinclair'     , '2.1.1'
gem 'activesupport', '7.2.2.1'

group :development, :test do
  gem 'pry',        '0.15.2'
  gem 'pry-nav',    '1.0.0'
  gem 'simplecov',  '0.22.0'
  gem 'rubycritic', '4.9.1'
  gem 'yard',       '0.9.37'
  gem 'yardstick',  '0.9.9'
end

group :development do
  gem 'reek',          '6.4.0'
  gem 'rubocop',       '1.73.1'
  gem 'rubocop-rspec', '3.5.0'
end

group :test do
  gem 'minitest',                  '5.25.4'
  gem 'rspec',                     '3.13.0'
  gem 'rspec-collection_matchers', '1.2.1'
  gem 'rspec-core',                '3.13.3'
  gem 'rspec-expectations',        '3.13.3'
  gem 'rspec-mocks',               '3.13.2'
  gem 'rspec-support',             '3.13.2'
end
