source 'https://rubygems.org'
ruby '3.3.1'


gem 'bundler',  '2.6.8'
gem 'rake',     '13.2.1'
gem 'sinclair', '3.0.0'

gem 'activesupport',            '7.2.2.1'
gem 'actionpack',               '7.2.2.1'
gem 'activerecord',             '7.2.2.1'
gem 'actionview',               '7.2.2.1'
gem 'rack',                     '2.2.6.3'
gem 'rails',                    '7.2.2.1'
gem 'nokogiri',                 '1.14.4'
gem 'rails-controller-testing', '1.0.5'
gem 'sqlite3',                  '1.4.2'

group :development, :test do
  gem 'factory_bot', '6.2.1'
  gem 'pry',         '0.14.2'
  gem 'pry-nav',     '1.0.0'
  gem 'simplecov',   '0.22.0'
  gem 'rubycritic',  '4.9.2'
  gem 'yard',        '0.9.37'
  gem 'yardstick',   '0.9.9'
end

group :development do
  gem 'reek',          '6.4.0'
  gem 'rubocop',       '1.75.5'
  gem 'rubocop-rspec', '3.6.0'
end

group :test do
  gem 'minitest',           '5.25.4'
  gem 'rspec',              '3.13.0'
  gem 'rspec-core',         '3.13.3'
  gem 'rspec-expectations', '3.13.3'
  gem 'rspec-mocks',        '3.13.2'
  gem 'rspec-rails',        '6.0.2'
  gem 'rspec-support',      '3.13.2'
end
