source 'https://rubygems.org'
ruby '2.5.0'


gem 'bundler',  '1.16.1'
gem 'rake',     '13.0.3'
gem 'sinclair', '1.6.7'

gem 'actionpack',               '5.2.6'
gem 'activerecord',             '5.2.6'
gem 'actionview',               '5.2.6'
gem 'rack',                     '2.2.3'
gem 'rails',                    '5.2.6'
gem 'factory_bot',              '5.2.0'
gem 'nokogiri',                 '1.11.4'
gem 'rails-controller-testing', '1.0.4'
gem 'sqlite3',                  '1.4.2'

group :development, :test do
  gem 'pry',        '0.12.2'
  gem 'pry-nav',    '0.3.0'
  gem 'simplecov',  '0.17.1'
  gem 'rubycritic', '4.6.1'
  gem 'yard',       '0.9.26'
  gem 'yardstick',  '0.9.9'
end

group :development do
  gem 'reek',          '6.0.3'
  gem 'rubocop',       '0.80.1'
  gem 'rubocop-rspec', '1.38.1'
end

group :test do
  gem 'rspec',              '3.9.0'
  gem 'rspec-core',         '3.9.3'
  gem 'rspec-expectations', '3.9.4'
  gem 'rspec-mocks',        '3.9.1'
  gem 'rspec-rails',        '3.9.1'
  gem 'rspec-support',      '3.9.4'
end
