source 'https://rubygems.org'
ruby '2.5.0'

gem 'bundler',      '~> 1.16.1'
gem 'rails',        '~> 5.2.3'
gem 'sass-rails',   '~> 5.0.x'
gem 'uglifier',     '>= 1.3.0'
gem 'nokogiri',     '>= 1.10.2'
gem 'bower-rails',  '~> 0.11.0'
gem 'rake',         '>= 12.3.1'
gem 'turbolinks',   '~> 5.2.x'
gem 'newrelic_rpm', '~> 6.2.x'
gem 'tarquinn',     '0.1.0'
gem 'sinclair',     '~> 1.4.1'

gem 'darthjee-core_ext', '>= 1.7.4'

group :development, :test do
  gem 'factory_bot',   '5.0.2'
  gem 'zonebie',       '0.6.1'
  gem 'pry-nav',       '~> 0.2.4'
  gem 'pry-rails',     '0.3.9'
  gem 'rspec',         '>= 3.8'
  gem 'rspec-rails',   '3.8.2'
  gem 'rubocop',       '0.58.1'
  gem 'rubocop-rspec', '1.30.0'
  gem 'rubycritic',    '>= 4.0.2'
  gem 'simplecov',     '~> 0.16.x'
  gem 'yard',          '>= 0.9.18'
  gem 'yardstick',     '>= 0.9.9'

  gem 'rspec-collection_matchers', '1.1.3'
  gem 'rails-controller-testing',  '1.0.4'
end

group :test do
  gem 'simplecov', '~> 0.16.x'
  gem 'webmock',   '3.5.1'
end
