source 'https://rubygems.org'
ruby '2.5.0'

gem 'bundler', '1.16.1'
gem 'rake',    '13.0.1'

group :development, :test do
  gem 'pry',        '0.12.2'
  gem 'pry-nav',    '0.3.0'
  gem 'simplecov',  '0.17.1'
  gem 'rubycritic', '4.4.1'
  gem 'yard',       '0.9.24'
  gem 'yardstick',  '0.9.9'
end

group :development do
  gem 'reek',          '5.6.0'
  gem 'rubocop',       '0.80.1'
  gem 'rubocop-rspec', '1.38.1'
end

group :test do
  gem 'rspec',              '3.9.0'
  gem 'rspec-core',         '3.9.1'
  gem 'rspec-expectations', '3.9.1'
  gem 'rspec-mocks',        '3.9.1'
  gem 'rspec-support',      '3.9.2'
end
