source 'https://rubygems.org'
ruby '2.5.0'

gem 'azeroth',           '0.7.2'
gem 'bower-rails',       '0.12.0'
gem 'bundler',           '1.16.1'
gem 'darthjee-core_ext', '2.0.0'
gem 'newrelic_rpm',      '6.8.0.360'
gem 'nokogiri',          '1.10.10'
gem 'puma',              '4.3.5'
gem 'rack',              '2.2.3'
gem 'rails',             '5.2.4.3'
gem 'rake',              '13.0.1'
gem 'sass-rails',        '5.1.0'
gem 'sinclair',          '1.6.7'
gem 'jace',              '0.0.3'
gem 'uglifier',          '4.2.0'
gem 'tarquinn',          '0.1.0'
gem 'turbolinks',        '5.2.1'
gem 'magicka',           '0.5.4'

group :development, :test do
  gem 'pry',        '0.12.2'
  gem 'pry-nav',    '0.3.0'
  gem 'pry-rails',  '0.3.9'
  gem 'rubycritic', '4.4.1'
  gem 'simplecov',  '0.17.1'
  gem 'yard',       '0.9.24'
  gem 'yardstick',  '0.9.9'
end

group :development do
  gem 'reek',          '5.6.0'
  gem 'rubocop',       '0.80.1'
  gem 'rubocop-rspec', '1.38.1'
  gem 'zonebie',       '0.6.1'
  gem 'web-console',   '3.7.0'
end

group :test do
  gem 'factory_bot',               '5.1.1'
  gem 'rails-controller-testing',  '1.0.4'
  gem 'rspec',                     '3.9.0'
  gem 'rspec-collection_matchers', '1.2.0'
  gem 'rspec-core',                '3.9.1'
  gem 'rspec-expectations',        '3.9.0'
  gem 'rspec-mocks',               '3.9.1'
  gem 'rspec-rails',               '3.9.0'
  gem 'rspec-support',             '3.9.2'
  gem 'shoulda-matchers',          '4.3.0'
  gem 'timecop',                   '0.9.1'
  gem 'webmock',                   '3.8.2'
end
