source 'https://rubygems.org'
ruby '2.5.0'

gem 'rails', '~> 5.2.x'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'turbolinks'
gem 'nokogiri', '>= 1.8.2'

gem 'arstotzka', '1.0.3'
gem 'darthjee-core_ext', '>= 1.7.3'
gem 'tarquinn', '0.1.0'
gem 'bower-rails', '~> 0.11.0'
gem 'sinclair', '1.1.2'
gem 'rake', '>= 12.3'
gem 'danica', '>= 2.7.4'

group :development, :test do
  gem 'factory_bot'
  gem 'rspec-rails'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'zonebie'
  gem 'simplecov'
  gem 'rspec-collection_matchers'
  gem 'rails-controller-testing'
end

group :test do
  gem 'webmock'
end
