source 'https://rubygems.org'
ruby '2.7.0'


gem 'bundler',  '2.1.8'
gem 'rake',     '13.0.6'
gem 'sinclair', '1.6.7'

gem 'actionpack',               '5.2.6'
gem 'activerecord',             '5.2.6'
gem 'actionview',               '5.2.6'
gem 'rack',                     '2.2.3'
gem 'rails',                    '5.2.6'
gem 'factory_bot',              '6.2.1'
gem 'nokogiri',                 '1.13.5'
gem 'rails-controller-testing', '1.0.5'
gem 'sqlite3',                  '3.1.4.2'

group :development, :test do
  gem 'pry',        '0.14.1'
  gem 'pry-nav',    '1.0.0'
  gem 'simplecov',  '0.21.2'
  gem 'rubycritic', '4.7.0'
  gem 'yard',       '0.9.27'
  gem 'yardstick',  '0.9.9'
end

group :development do
  gem 'reek',          '6.0.3'
  gem 'rubocop',       '0.80.1'
  gem 'rubocop-rspec', '1.38.1'
end

group :test do
  gem 'rspec',              '3.11.0'
  gem 'rspec-core',         '3.11.0'
  gem 'rspec-expectations', '3.11.0'
  gem 'rspec-mocks',        '3.11.1'
  gem 'rspec-rails',        '5.1.2'
  gem 'rspec-support',      '3.11.0'
end
