source 'https://rubygems.org'
ruby '3.3.1'

gem 'bundler',       '2.5.13'
gem 'rake',          '13.2.1'
gem 'sinclair'     , '3.0.1'
gem 'activesupport', '7.2.2.1'

group :development, :test do
  gem 'pry',            '0.14.2'
  gem 'pry-nav',        '1.0.0'
  gem 'simplecov',      '0.22.0'
  gem 'simplecov-html', '0.13.2''
  gem 'simplecov-lcov', '0.9.0'
  gem 'rubycritic',     '5.0.0'
  gem 'yard',           '0.9.38'
  gem 'yardstick',      '0.9.9'
end

group :development do
  gem 'reek',          '6.5.0'
  gem 'rubocop',       '1.85.1'
  gem 'rubocop-rspec', '3.9.0'
end

group :test do
  gem 'rspec',                   '3.13.2'
  gem 'rspec-collection_matchers', '1.2.1'
  gem 'rspec-core',                '3.13.6'
  gem 'rspec-expectations',        '3.13.5'
  gem 'rspec-mocks',               '3.13.8'
  gem 'rspec-support',             '3.13.7'
end
