source 'https://rubygems.org'
ruby '2.5.0'

gem 'bundler',            '1.16.1'
gem 'puma',               '4.3.1'
gem 'rack',               '2.1.1'
gem 'rake',               '13.0.1'

gem 'rails',        '5.2.4.1'
gem 'sass-rails',   '5.1.0'
gem 'uglifier',     '4.2.0'
gem 'nokogiri',     '1.10.8'
gem 'bower-rails',  '0.12.0'
gem 'turbolinks',   '5.2.1'
gem 'newrelic_rpm', '6.9.0.363'

gem 'darthjee-core_ext', '2.0.0'
