source 'https://rubygems.org'
ruby '2.7.0'

gem 'bundler',           '2.4.8'
gem 'darthjee-core_ext', '2.0.0'
gem 'puma',              '6.0.0'
gem 'rack',              '2.2.5'
gem 'rake',              '13.0.6'
gem 'rails',             '5.2.8.1'
gem 'sass-rails',        '6.0.0'
gem 'uglifier',          '4.2.0'
gem 'nokogiri',          '1.13.10'
gem 'bower-rails',       '0.12.0'
gem 'turbolinks',        '5.2.1'
gem 'newrelic_rpm',      '8.12.0'
gem 'sinclair',          '2.0.1'
gem 'tzinfo-data'

group :development, :test do
  gem 'pry',        '0.14.2'
  gem 'pry-nav',    '1.0.0'
  gem 'pry-rails',  '0.3.9'
  gem 'simplecov',  '0.21.2'
  gem 'yard',       '0.9.34'
  gem 'yardstick',  '0.9.9'
  gem 'zyra',       '1.1.0'
end

group :development do
  gem 'rubycritic',    '4.8.0'
  gem 'reek',          '6.1.4'
  gem 'rubocop',       '1.51.0'
  gem 'rubocop-rspec', '2.22.0'
  gem 'zonebie',       '0.6.1'
  gem 'web-console',   '3.7.0'
end

group :test do
  gem 'factory_bot',               '6.2.1'
  gem 'rails-controller-testing',  '1.0.5'
  gem 'rspec',                     '3.12.0'
  gem 'rspec-collection_matchers', '1.2.0'
  gem 'rspec-core',                '3.12.2'
  gem 'rspec-expectations',        '3.12.3'
  gem 'rspec-mocks',               '3.12.5'
  gem 'rspec-rails',               '5.1.2'
  gem 'rspec-support',             '3.12.0'
  gem 'shoulda-matchers',          '4.3.0'
  gem 'timecop',                   '0.9.1'
  gem 'webmock',                   '3.8.2'
end
