source 'https://rubygems.org'
ruby '3.3.1'


gem 'bundler',  '2.5.13'
gem 'rake',     '13.2.1'
gem 'sinclair', '3.1.0'

gem 'activesupport',            '7.2.2.1'
gem 'actionpack',               '7.2.2.1'
gem 'activerecord',             '7.2.2.1'
gem 'actionview',               '7.2.2.1'
gem 'rack'#,                     '2.2.6.3'
gem 'rails',                    '7.2.2.1'
gem 'nokogiri'#,                 '1.19.1'
gem 'rails-controller-testing'#, '1.0.5'
gem 'sqlite3',                  '1.4.2'

group :development, :test do
  gem 'factory_bot',    '6.5.6'
  gem 'pry',            '0.14.2'
  gem 'pry-nav',        '1.0.0'
  gem 'simplecov',      '0.22.0'
  gem 'simplecov-html', '0.13.2'
  gem 'simplecov-lcov', '0.9.0'
  gem 'rubycritic',     '5.0.0'
  gem 'yard',           '0.9.38'
  gem 'yardstick',      '0.9.9'
end

group :development do
  gem 'reek',          '6.5.0'
  gem 'rubocop',       '1.85.1'
  gem 'rubocop-rspec', '3.9.0'
  gem 'rubocop-factory_bot',      '2.28.0'
  gem 'rubocop-rails',            '2.34.3'
  gem 'rubocop-rake',             '0.7.1'
  gem 'rubocop-rspec',            '3.9.0'
  gem 'rubocop-rspec_rails',      '2.32.0'
end

group :test do
  gem 'rspec',              '3.13.2'
  gem 'rspec-core',         '3.13.6'
  gem 'rspec-expectations', '3.13.5'
  gem 'rspec-mocks',        '3.13.8'
  gem 'rspec-rails',        '8.0.3'
  gem 'rspec-support',      '3.13.7'
end
